name: Inject Access Token

on:
  push:
    branches:
      - main

jobs:
  inject-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Inject Token into Code
        run: |
          sed -i "s/ACCESS_TOKEN_PLACEHOLDER/${{ secrets.ACCESS_TOKEN }}/g" src/main.js
        working-directory: ${{ github.workspace }}

      - name: Build and Deploy to GitHub Pages
        run: npm run build && npm run deploy
        working-directory: ${{ github.workspace }}
